from entities.location import Location
class List_main():
    list_name = "Основной"
    list_of_location = []
    # Заполнение
    list_of_location.append(Location("База террористов", "images/default/terror_base.jpg"))
    list_of_location.append(Location("Банк", "images/default/bank.jpg"))
    list_of_location.append(Location("Больница", "images/default/hospital.jpg"))
    list_of_location.append(Location("Киностудия", "images/default/kinostudio.jpg"))
    list_of_location.append(Location("Корпоратив", "images/default/corporate_disco.jpg"))
    list_of_location.append(Location("Киностудия", "images/default/kinostudio.jpg"))
    list_of_location.append(Location("Партизанский отряд", "images/default/partisane_team.jpg"))
    list_of_location.append(Location("Пассажирский поезд", "images/default/train.jpg"))
    list_of_location.append(Location("Пиратский корабль", "images/default/pirate_ship.jpg"))
    list_of_location.append(Location("Полярная станция", "images/default/polar_station.jpg"))
    list_of_location.append(Location("Посольство", "images/default/embassy.jpg"))
    list_of_location.append(Location("Ресторан", "images/default/restouran.jpg"))
    list_of_location.append(Location("Супермаркет", "images/default/supermarket.jpg"))
    list_of_location.append(Location("Театр", "images/default/teather.jpg"))
    list_of_location.append(Location("Университет", "images/default/university.jpg"))
    list_of_location.append(Location("Воинская часть", "images/default/military_union.jpg"))
    list_of_location.append(Location("Войско крестоносцев", "images/default/crusaders.jpg"))
    list_of_location.append(Location("Казино", "images/default/casino.jpg"))
    list_of_location.append(Location("Океанский лайнер", "images/default/ship.jpg"))
    list_of_location.append(Location("Орбитальная станция", "images/default/space_station.jpg"))
    list_of_location.append(Location("Отель", "images/default/hotel.jpg"))
    list_of_location.append(Location("Пляж", "images/default/beach.jpg"))
    list_of_location.append(Location("Подводная лодка", "images/default/underwater_sheep.jpg"))
    list_of_location.append(Location("Полицейский участок", "images/default/police.jpg"))
    list_of_location.append(Location("Самолет", "images/default/airplane.jpg"))
    list_of_location.append(Location("Спа-салон", "images/default/spa.jpg"))
    list_of_location.append(Location("СТО", "images/default/sto.jpg"))
    list_of_location.append(Location("Церковь", "images/default/chirch.jpg"))
    list_of_location.append(Location("Цирк", "images/default/circus.jpg"))
    list_of_location.append(Location("Школа", "images/default/school.jpg"))
