from entities.location import Location
class List_first_default():
    list_name = "1 (Основной)"
    list_of_location = []
    # Заполнение
    list_of_location.append(Location("База террористов", "images/first_default/terror_base.jpg"))
    list_of_location.append(Location("Банк", "images/first_default/bank.jpg"))
    list_of_location.append(Location("Больница", "images/first_default/hospital.jpg"))
    list_of_location.append(Location("Киностудия", "images/first_default/kinostudio.jpg"))
    list_of_location.append(Location("Корпоратив", "images/first_default/corporate_disco.jpg"))
    list_of_location.append(Location("Киностудия", "images/first_default/kinostudio.jpg"))
    list_of_location.append(Location("Партизанский отряд", "images/first_default/partisane_team.jpg"))
    list_of_location.append(Location("Пассажирский поезд", "images/first_default/train.jpg"))
    list_of_location.append(Location("Пиратский корабль", "images/first_default/pirate_ship.jpg"))
    list_of_location.append(Location("Полярная станция", "images/first_default/polar_station.jpg"))
    list_of_location.append(Location("Посольство", "images/first_default/embassy.jpg"))
    list_of_location.append(Location("Ресторан", "images/first_default/restouran.jpg"))
    list_of_location.append(Location("Супермаркет", "images/first_default/supermarket.jpg"))
    list_of_location.append(Location("Театр", "images/first_default/teather.jpg"))
    list_of_location.append(Location("Университет", "images/first_default/university.jpg"))
    list_of_location.append(Location("Воинская часть", "images/first_default/military_union.jpg"))
    list_of_location.append(Location("Войско крестоносцев", "images/first_default/crusaders.jpg"))
    list_of_location.append(Location("Казино", "images/first_default/casino.jpg"))
    list_of_location.append(Location("Океанский лайнер", "images/first_default/ship.jpg"))
    list_of_location.append(Location("Орбитальная станция", "images/first_default/space_station.jpg"))
    list_of_location.append(Location("Отель", "images/first_default/hotel.jpg"))
    list_of_location.append(Location("Пляж", "images/first_default/beach.jpg"))
    list_of_location.append(Location("Подводная лодка", "images/first_default/underwater_sheep.jpg"))
    list_of_location.append(Location("Полицейский участок", "images/first_default/police.jpg"))
    list_of_location.append(Location("Самолет", "images/first_default/airplane.jpg"))
    list_of_location.append(Location("Спа-салон", "images/first_default/spa.jpg"))
    list_of_location.append(Location("СТО", "images/first_default/sto.jpg"))
    list_of_location.append(Location("Церковь", "images/first_default/chirch.jpg"))
    list_of_location.append(Location("Цирк", "images/first_default/circus.jpg"))
    list_of_location.append(Location("Школа", "images/first_default/school.jpg"))
