from entities.location import Location


class List_second_dlc():
        list_name = "Дополнительный"
        list_of_location = []
        list_of_location.append(Location("Стрип-клуб", "images/second_dlc/strip.jpg"))        
        list_of_location.append(Location("Зона 51", "images/second_dlc/area_51.jpg")) 
        list_of_location.append(Location("Зоопарк", "images/second_dlc/zoopark.jpg"))     
        list_of_location.append(Location("Стройплощадка", "images/second_dlc/stroika.jpg"))     
        list_of_location.append(Location("Тюрьма", "images/second_dlc/aye.jpg"))      
        list_of_location.append(Location("Ночной клуб", "images/second_dlc/club.jpg"))        
        list_of_location.append(Location("Бар", "images/second_dlc/bar.jpg"))        
        list_of_location.append(Location("Метро", "images/second_dlc/metro.jpg"))       
        list_of_location.append(Location("Кинотеатр", "images/second_dlc/kino.jpg"))      
        list_of_location.append(Location("Кузница", "images/second_dlc/kyznica.jpg"))     
        list_of_location.append(Location("Музей", "images/second_dlc/museim.jpg"))      
        list_of_location.append(Location("Лес", "images/second_dlc/forest.jpg"))    
        list_of_location.append(Location("Спортзал", "images/second_dlc/gym.jpg"))       
        list_of_location.append(Location("Столовая", "images/second_dlc/stolovka.jpg"))     
        list_of_location.append(Location("ЗАГС", "images/second_dlc/zags.jpg"))      
        list_of_location.append(Location("Суд", "images/second_dlc/syd.jpg"))     
        list_of_location.append(Location("Свалка", "images/second_dlc/pomoika.jpg"))
        list_of_location.append(Location("Рок-концерт", "images/second_dlc/consert.jpg"))    
        list_of_location.append(Location("Псих-больница", "images/second_dlc/psih.jpg"))   
        list_of_location.append(Location("Пустыня", "images/second_dlc/duna.jpg"))    
        list_of_location.append(Location("Рай", "images/second_dlc/heaven.jpg"))  
        list_of_location.append(Location("Ад", "images/second_dlc/hell.jpg"))
        list_of_location.append(Location("Чернобыль", "images/second_dlc/stalker.jpg"))
        list_of_location.append(Location("Завод", "images/second_dlc/zavod.jpg"))
        list_of_location.append(Location("Худ. мастерская", "images/second_dlc/art_room.jpg"))
        list_of_location.append(Location("Ферма", "images/second_dlc/rancho.jpg"))
        list_of_location.append(Location("Кладбище", "images/second_dlc/grave.jpg"))
        list_of_location.append(Location("Болото", "images/second_dlc/boloto.jpg"))
        list_of_location.append(Location("Замок", "images/second_dlc/castle.jpg"))
        list_of_location.append(Location("Баня", "images/second_dlc/banya.jpg"))
